name: rust ci
on:
  push:
    branches:
    - main
  pull_request:
    # Don't run on documentation-only changes
    paths-ignore: ["**.md"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@a35f858a9bcd26fc0c80928ac8b0a85c0f791c06
    with:
      bench: false
      os: ubuntu-24.04